try this

diff --git a/.github/workflows/mypy.yml b/.github/workflows/mypy.yml
--- a/.github/workflows/mypy.yml
+++ b/.github/workflows/mypy.yml
@@ -16,19 +16,19 @@ jobs:
           # Convert python-version to a string that tox understands
           - python-version: "3.7"
             tox-py-version: "37"
-            continue-on-mypy-error: "true"
+            ignore-mypy-error: "true"
           - python-version: "3.8"
             tox-py-version: "38"
-            continue-on-mypy-error: "true"
+            ignore-mypy-error: "true"
           - python-version: "3.9"
             tox-py-version: "39"
-            continue-on-mypy-error: "true"
+            ignore-mypy-error: "true"
           - python-version: "3.10"
             tox-py-version: "310"
-            continue-on-mypy-error: "false"
+            ignore-mypy-error: "false"
           - python-version: "3.11-dev"
             tox-py-version: "311"
-            continue-on-mypy-error: "false"
+            ignore-mypy-error: "false"
 
     steps:
       - uses: actions/checkout@v3
@@ -39,26 +39,16 @@ jobs:
       - name: Install build tools
         run: |
           python -m pip install --upgrade pip setuptools tox
-      - name: Echo matrix config
-        run: |
-          echo "Python version: ${{ matrix.python-version }}"
-          echo "continue-on-mypy-error: ${{ matrix.continue-on-mypy-error }}"
-          echo "jsonified: ${{ fromJSON( matrix.continue-on-mypy-error ) }}"
-          echo "jsonified (negative): ${{ ! fromJSON( matrix.continue-on-mypy-error ) }}"
 
       # Ignore mypy errors for known buggy behaviour of mypy with older pythons
-      - name: Mypy (ignore failure)
-        if: ${{ fromJSON( matrix.continue-on-mypy-error ) }}
-        run: |
-          tox -e py${{ matrix.tox-py-version }}-mypy || true
+#      - name: Mypy (ignore failure)
+#        if: ${{ fromJSON( matrix.ignore-mypy-error ) }}
+#        run: |
+#          tox -e py${{ matrix.tox-py-version }}-mypy || true
 
       # Otherwise, require the mypy run to succeed
       - name: Mypy
-        if: ${{ ! fromJSON( matrix.continue-on-mypy-error ) }}
+#        if: ${{ ! fromJSON( matrix.ignore-mypy-error ) }}
+        continue-on-error: ${{ fromJSON( matrix.ignore-mypy-error ) }}
         run: |
           tox -e py${{ matrix.tox-py-version }}-mypy
-
-      - name: Should I ignore mypy failure?
-        if: "matrix.continue-on-mypy-error"
-        run: |
-          echo "yes"
